name: Selenium TestNG Pipeline

on:
  workflow_dispatch: # Enables manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Adjust to your project's Java version
          distribution: 'temurin' # Eclipse Temurin is a popular JDK distribution

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Step 4: Build and run tests with Maven
      - name: Build and test
        run: mvn clean test

      # Step 5: Upload test reports (optional, for debugging)
      - name: Upload TestNG reports
        if: always() # Uploads even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: test-output/