name: Run Selenium TestNG Tests

on:
  workflow_dispatch:    # Manual trigger
  schedule:
    - cron: '0 12 * * *' # Every day at 12:00 UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Use 17 since Java 23 caused issues

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Run Tests with Maven
        run: mvn clean test

      - name: Upload TestNG Reports (XML + HTML)
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Reports
          path: |
            target/surefire-reports/
            test-output/             # TestNG default HTML reports
