name: Run TestNG Tests

on:
  workflow_dispatch:     # Manual trigger from GitHub UI
  schedule:
    - cron: '0 23 * * *'  # Scheduled: Every day at 11 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run TestNG Suite
        run: mvn test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testng-report
          path: target/surefire-reports/
